version: "3"

services:
  servers_registry:
    build:
      context: ./
    ports:
      - "7000:8000"

  rembg:
    build:
      context: ./servers/serverkit-rembg
    depends_on:
      - servers_registry

  stardist:
    build:
      context: ./servers/serverkit-stardist
    depends_on:
      - servers_registry

  mousetumornet:
    build:
      context: ./servers/serverkit-mousetumornet
    depends_on:
      - servers_registry
    ipc: host

  spam:
    build:
      context: ./servers/serverkit-spam
    depends_on:
      - servers_registry

  tau-fibrils-yolo:
    build:
      context: ./servers/serverkit-tau-fibrils-yolo
    depends_on:
      - servers_registry

  orientationpy:
    build:
      context: ./servers/serverkit-orientationpy
    depends_on:
      - servers_registry

  skimage:
    build:
      context: ./servers/serverkit-skimage
    depends_on:
      - servers_registry

  trackpy:
    build:
      context: ./servers/serverkit-trackpy
    depends_on:
      - servers_registry

  cellpose:
    build:
      context: ./servers/serverkit-cellpose
    depends_on:
      - servers_registry
  
  instanseg:
    build:
      context: ./servers/serverkit-instanseg
    depends_on:
      - servers_registry
  
  spotiflow:
    build:
      context: ./servers/serverkit-spotiflow
    depends_on:
      - servers_registry
  
  sam2-auto:
    build:
      context: ./servers/serverkit-sam2
      dockerfile: Dockerfile.auto
    depends_on:
      - servers_registry
  
  sam2-points:
    build:
      context: ./servers/serverkit-sam2
      dockerfile: Dockerfile.points
    depends_on:
      - servers_registry
  
  sam2-boxes:
    build:
      context: ./servers/serverkit-sam2
      dockerfile: Dockerfile.boxes
    depends_on:
      - servers_registry
  
  sam2-video:
    build:
      context: ./servers/serverkit-sam2
      dockerfile: Dockerfile.video
    depends_on:
      - servers_registry
